#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 015

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 015: Spec Approval Mechanism"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Frontend (Port 3000)
echo ""
echo -e "${YELLOW}Starting Frontend Service...${NC}"
cd apps/frontend
npm run dev &
FRONTEND_PID=$!
cd ../..
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "Key Files to Modify:"
echo "  Backend:"
echo "    - apps/backend/spec/pipeline/orchestrator.py"
echo "    - apps/backend/runners/spec_runner.py"
echo "    - apps/frontend/src/main/project-store.ts"
echo "  Frontend:"
echo "    - apps/frontend/src/renderer/stores/task-store.ts"
echo "    - apps/frontend/src/renderer/components/task-detail/TaskActions.tsx"
echo "    - apps/frontend/src/renderer/components/task-detail/SpecReviewModal.tsx (new)"
echo ""
echo "To stop services:"
echo "  kill $FRONTEND_PID"
echo ""
