#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INVESTIGATION WORKFLOW
# ============================================

echo ""
echo "========================================"
echo "Investigation Workflow"
echo "========================================"
echo ""
echo "This is an INVESTIGATION workflow."
echo "No services need to be started for investigation phase."
echo ""
echo "Phase 1: Reproduce & Locate Error"
echo "  - Search logs and crash traces"
echo "  - Identify missing file path"
echo "  - Check git history"
echo ""
echo "Phase 2: Analyze Root Cause"
echo "  - Analyze task runner code"
echo "  - Understand crash loop mechanism"
echo "  - Formulate fix strategy"
echo ""
echo "Phase 3: Implement Fix (blocked until investigation complete)"
echo ""
echo "========================================"
echo "Environment Ready for Investigation"
echo "========================================"
echo ""
echo "Backend Path: apps/backend"
echo "Project Root: ."
echo ""
echo "Key Investigation Files:"
echo "  - Error logs in: logs/"
echo "  - Task logs in: .auto-claude/specs/"
echo "  - Backend code in: apps/backend/"
echo ""
echo "To start investigation:"
echo "  python apps/backend/run.py --spec 020"
echo ""
