#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 110-implement-full-autonomous-pr-review-system

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# SETUP BACKEND
# ============================================

echo ""
echo "Setting up Backend..."

cd apps/backend

# Check if virtual environment exists
if [ ! -d ".venv" ]; then
    echo -e "${YELLOW}Creating virtual environment...${NC}"
    uv venv
fi

# Activate virtual environment
source .venv/bin/activate

# Install dependencies
echo "Installing backend dependencies..."
uv pip install -r requirements.txt

# Install new dependencies for this feature
echo "Installing new PR review dependencies..."
uv pip install structlog>=25.5.0 pybreaker>=1.3.0 filelock>=3.20.0

# Return to root
cd ../..

# ============================================
# SETUP FRONTEND
# ============================================

echo ""
echo "Setting up Frontend..."

cd apps/frontend

# Install dependencies
if [ ! -d "node_modules" ]; then
    echo "Installing frontend dependencies..."
    npm install
fi

# Return to root
cd ../..

# ============================================
# START SERVICES (Development Mode)
# ============================================

echo ""
echo "========================================"
echo "To start development servers:"
echo "========================================"
echo ""
echo "Backend:"
echo "  cd apps/backend && source .venv/bin/activate"
echo "  python run.py --spec 110"
echo ""
echo "Frontend (separate terminal):"
echo "  cd apps/frontend && npm run dev"
echo ""
echo "========================================"
echo "Environment Setup Complete!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  Python CLI (apps/backend/)"
echo "  Frontend: http://localhost:3000 (Electron dev)"
echo ""
echo "To run the spec:"
echo "  cd apps/backend && source .venv/bin/activate && python run.py --spec 110"
echo ""
